# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: research
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Publications
    identifier: pubs
    url: /
    weight: 40
  - name: Full Publications
    parent: pubs
    url: fullpub/Publications.pdf
    weight: 20
  - name: Recent Publications
    parent: pubs
    url: publication
    weight: 10
  - name: "What's New"
    url: news
    weight: 50
  - name: Contact
    url: contact
    weight: 60
    
